name: Code Formatter

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Latest Changes
        run: git fetch origin

      - name: Get Changed Files
        id: diff
        run: |
          git fetch origin
          git diff --name-only origin/main..HEAD > changed_files.txt
          echo "Changed files: $(cat changed_files.txt)"

      - name: Run Python Formatter on Changed Files
        run: |
          python3 scripts/python_script.py

      - name: Commit formatted files
        run: git commit -am "Formatted changed lines"
