name: Code Formatter

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Latest Changes
        run: git fetch origin

      - name: Check if PR event
        run: |
          if [[ $GITHUB_EVENT_NAME != "pull_request" ]]; then
            echo "Not a pull request event. Exiting."
            exit 0
          fi

      - name: Install clang-format and Python
        run: |
          sudo apt-get update
          sudo apt-get install clang-format python3

      - name: Get Changed Files
        id: diff
        run: |
          git fetch origin
          git diff --name-only origin/main..HEAD > changed_files.txt
          echo "Changed files: $(cat changed_files.txt)"

      - name: Show diff before formatting
        run: |
          echo "Showing the diff before formatting:"
          git diff origin/main..HEAD

      - name: Run Python Formatter on Changed Files
        run: |
          python3 scripts/python_script.py   # Path to your Python script

      - name: Show diff after formatting
        run: |
          echo "Showing the diff after formatting:"
          git diff origin/main..HEAD

      - name: Commit formatted files
        run: git commit -am "Formatted changed lines"
