name: Format Code with Clang-Format

on:
  pull_request:
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'
    types: [opened, synchronize, reopened]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Clang-Format and Python
      run: |
        sudo apt-get update
        sudo apt-get install clang-format
        sudo apt-get install python3
       
        

    - name: Identify the modified files
      id: modified-files
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > modified_files.txt
        cat modified_files.txt

    

    - name: Run Python script to format only changed lines
      run: |
        python3 scripts/python_script.py
