name: Clang Format Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the full history is fetched for PR diff

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Fetch base branch and check for clang-format
        run: |
          git fetch origin main:main
          if [ $? -ne 0 ]; then
            echo "Failed to fetch the 'main' branch from origin."
            exit 1
          fi
          
          output=$(git-clang-format origin/main --diff)
          echo "$output"
          if ! echo "$output" | grep -q "no modified files to format"; then
            echo "Code formatting issues detected."
            echo "Run the following command locally to fix them:"
            echo "  git-clang-format origin/main"
            echo "After applying the changes, commit and push them to your branch."
            exit 1
          fi


