name: Clang Format Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install clang-format and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format python3

      - name: Get changed lines and run clang-format
        run: |
          git fetch origin main
          
          # Get the diff between main and the PR branch
          git diff origin/main...HEAD > changes.diff

          # Run clang-format-diff.py on the diff
          curl -sSL https://raw.githubusercontent.com/llvm/llvm-project/main/clang/tools/clang-format/clang-format-diff.py -o clang-format-diff.py
          chmod +x clang-format-diff.py

          FORMAT_OUTPUT=$(python3 clang-format-diff.py -p1 -style=file < changes.diff)

          if [ -n "$FORMAT_OUTPUT" ]; then
            echo "Clang-format found formatting issues:"
            echo "$FORMAT_OUTPUT"
            echo "$FORMAT_OUTPUT" > format.patch
            cat format.patch
            exit 1
          else
            echo "No formatting issues found."
          fi
