name: Clang Format Check

on:
  push:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'
    
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'
    

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the full history is fetched

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format and show differences
        run: |
          # Run clang-format on the relevant files directly
          clang-format -i $(git diff --name-only --diff-filter=ACMRTUXB origin/main...HEAD -- '*.c' '*.cpp' '*.cc' '*.cxx' \
                    '*.java' '*.js' '*.json' '*.m' '*.h' '*.proto' '*.cs')

          # Check if the code is formatted correctly
          if ! git diff --quiet; then
            echo "Code not formatted correctly. Showing diff:"
            git diff --color
            exit 1
          fi
