name: Clang Tidy Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy

      - name: Find modified, new, and PR files
        id: find_files
        run: |
          # Get the files modified in the last commit (including new files)
          files=$(git diff --name-only HEAD~1 -- '*.cpp' '*.h')
          
          # Get untracked files (new files not staged)
          new_files=$(git ls-files --others --exclude-standard '*.cpp' '*.h')
          
          # Check if it's a pull request and get files changed in PR
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            pr_files=$(git diff --name-only origin/main...HEAD -- '*.cpp' '*.h')
          else
            pr_files=""
          fi
          
          # Combine modified files, new files, and PR files, remove duplicates
          all_files=$(echo -e "$files\n$new_files\n$pr_files" | sort -u | tr '\n' ' ')
          
          # Set the environment variable for the next step
          echo "FILES=$all_files" >> $GITHUB_ENV
          echo "Checking files: $all_files"
      
      - name: Run clang-tidy on files
        run: |
          # Check if there are any files to process
          if [ -n "$FILES" ]; then
            for file in $FILES; do
              # Run clang-tidy on each file
              clang-tidy $file -- -Iinclude
              
              # Check if clang-tidy failed (non-zero exit code)
              if [ $? -ne 0 ]; then
                echo "Clang-tidy check failed for file: $file"
                echo "Displaying diff for the failed file: $file"
                
                # Show the diff of the changes
                git diff $file
                exit 1 # Exit with error to fail the job if clang-tidy fails
              fi
            done
          else
            echo "No relevant files to check."
          fi
