name: Clang Format Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the full history is fetched for PR diff

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Fetch base branch and check for clang-format
        run: |
          # Fetch the base branch for comparison
          git fetch origin main:main

          # Check if the git fetch was successful
          if [ $? -ne 0 ]; then
            echo "Failed to fetch the 'main' branch from origin."
            exit 1
          fi

          # Run git-clang-format to check diffs from the PR base
          output=$(git-clang-format origin/main --diff)

          echo "$output"

          if ! echo "$output" | grep -q "no modified files to format"; then
            echo "Code not formatted correctly. Please run clang-format."
            exit 1
          fi
