name: Clang Format Check on PR

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Make script executable
        run: chmod +x ./git-clang-format-modified.sh

      - name: Run clang-format on modified lines
        run: |
          # Find all modified files in the PR
          MODIFIED_FILES=$(git diff --name-only origin/main...HEAD -- '*.cpp' '*.h' '*.c' '*.cc' '*.cxx' \
                            '*.proto' '*.cs' '*.m' '*.java' '*.js' '*.json')
          
          # Loop over the modified files and run the git-clang-format-modified.sh script
          for file in $MODIFIED_FILES; do
            ./git-clang-format-modified.sh $file
          done

      - name: Check if code is formatted
        run: |
          if ! git diff --quiet; then
            echo "Code is not formatted properly. Showing the diff:"
            git diff --color
            exit 1
          else
            echo "Code is formatted correctly!"
          fi
