name: Clang Format Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the full history is fetched

      - name: Fetch latest changes from remote
        run: git fetch origin

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Find modified, new, and PR files
        id: find_files
        run: |
          # Check for modified files in the pull request (if it's a PR)
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            pr_files=$(git diff --name-only origin/main...HEAD -- '*.cpp' '*.h' '*.c' '*.cc' '*.cxx' \
                    '*.proto' '*.cs' '*.m' '*.java' '*.js' '*.json')
          else
            pr_files=""
          fi

          # Combine all files (modified, new, and PR files)
          all_files=$(echo -e "$pr_files" | sort -u | tr '\n' ' ')
          
          echo "FILES=$all_files" >> $GITHUB_ENV
          echo "Checking files: $all_files"

      - name: Identify modified lines
        id: modified_lines
        run: |
          # Identify modified lines
          if [ -n "$FILES" ]; then
            for file in $FILES; do
              echo "Checking file: $file"
              git diff --unified=0 origin/main...HEAD -- $file | \
                grep -E "^\+|^\-" > modified_lines.txt
            done
            echo "Modified lines saved in modified_lines.txt"
          else
            echo "No relevant files to check."
          fi

      - name: Run clang-format and show differences
        run: |
          if [ -n "$FILES" ]; then
            # Run clang-format only on modified files and lines
            for file in $FILES; do
              echo "Running clang-format on $file"
              clang-format -i $file

              # Compare with git diff to check if formatting has been applied correctly
              if ! git diff --quiet; then
                echo "Code not formatted correctly in $file. Showing diff:"
                git diff --color $file
                exit 1
              fi
            done
          else
            echo "No relevant files to check."
          fi
