name: Clang Format Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check clang-format on PR changes
        run: |
          git fetch origin main

          # Run git-clang-format to check diffs from the PR base
          output=$(git-clang-format origin/main --diff)

          echo "$output"

          if ! echo "$output" | grep -q "no modified files to format"; then
            echo "Code not formatted correctly. Please run clang-format."
            exit 1
          fi
