name: Format Code with Clang-Format

on:
  pull_request:
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'
    types: [opened, synchronize, reopened]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Clang-Format
      run: |
        sudo apt-get update
        sudo apt-get install clang-format

    - name: Identify the modified files
      id: modified-files
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > modified_files.txt
        cat modified_files.txt

    - name: Format only changed lines in existing files
      run: |
        # Loop through the modified files
        while read file; do
          # Check if file exists and is of the supported type
          if [[ $file =~ \.(c|cpp|cc|cxx|java|js|json|m|h|proto|cs)$ ]]; then
            # Check if the file is already committed in the repo
            if [[ -f "$file" ]]; then
              echo "Formatting $file"

              # Get the diff for changed lines
              git diff ${{ github.event.before }} ${{ github.sha }} -- $file > diff.txt

              # Apply clang-format only to the changed lines
              while read line; do
                if [[ $line =~ ^\+ ]]; then  # Lines added in the diff
                  echo "$line" | clang-format > formatted_line.txt
                  cat formatted_line.txt >> formatted_code.txt
                else
                  echo "$line" >> formatted_code.txt
                fi
              done < diff.txt

              # Overwrite the file with formatted content
              mv formatted_code.txt $file
              clang-format -i $file
            fi
          fi
        done < modified_files.txt

    - name: Show code diffs
      run: |
        echo "Showing differences between original and clang-formatted code:"
        git diff

    - name: Commit the formatted code
      run: |
        # Commit the changes made by clang-format
        git add .
        git diff --cached
        git commit -m "Apply clang-format to modified files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
