name: Clang Format Check

on:
  push:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'
    
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the full history is fetched

      - name: Fetch latest changes from remote
        run: git fetch origin

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format and show differences
        run: |
          # Debugging to check the current branch
          echo "Current branch: $(git branch --show-current)"

          # Check if it's a pull request
          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            echo "This is a PR"
            # PR changes - fetch the files modified in the PR or new commits to the PR
            pr_modified_files=$(git diff --name-only --diff-filter=ACMRTUXB origin/main...$GITHUB_SHA -- '*.c' '*.cpp' '*.cc' '*.cxx' \
              '*.java' '*.js' '*.json' '*.m' '*.h' '*.proto' '*.cs')
            
            echo "PR modified files: $pr_modified_files"

            pr_new_files=$(git ls-files --others --exclude-standard -- '*.c' '*.cpp' '*.cc' '*.cxx' \
              '*.java' '*.js' '*.json' '*.m' '*.h' '*.proto' '*.cs')
            
            echo "PR new files: $pr_new_files"
            
            all_files="$pr_modified_files $pr_new_files"

          else
            # Regular push to main branch
            echo "This is a push to main"
            modified_files=$(git diff --name-only --diff-filter=ACMRTUXB origin/main...HEAD -- '*.c' '*.cpp' '*.cc' '*.cxx' \
              '*.java' '*.js' '*.json' '*.m' '*.h' '*.proto' '*.cs')

            echo "modified files:$modified_files"

            new_files=$(git ls-files --others --exclude-standard -- '*.c' '*.cpp' '*.cc' '*.cxx' \
              '*.java' '*.js' '*.json' '*.m' '*.h' '*.proto' '*.cs')

            echo "new_files:$new_files"

            all_files="$modified_files $new_files"
          fi

          # Run clang-format on all relevant files
          if [ -n "$all_files" ]; then
            clang-format -i $all_files
          fi

          # Check if the code is formatted correctly
          if ! git diff --quiet; then
            echo "Code not formatted correctly. Showing diff:"
            git diff --color
            exit 1
          fi   