name: LLVM Header Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.cc'
      - '**/*.cxx'
      - '**/*.java'
      - '**/*.js'
      - '**/*.json'
      - '**/*.m'
      - '**/*.h'
      - '**/*.proto'
      - '**/*.cs'


jobs:
  header-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is fetched

      - name: Set up bash script
        run: |
          echo '#!/bin/bash' > check_header.sh
          echo "$(cat check_header.sh)" >> check_header.sh
          chmod +x check_header.sh

      - name: Check LLVM file headers
        run: |
          # Get the list of files changed in the pull request
          pr_files=$(git diff --name-only origin/main...HEAD -- '*.c' '*.cpp' '*.h' '*.cc' '*.cxx' '*.m')
          echo "pr_files:$pr_files"
          
          # Check the header in each file
          if [ -n "$pr_files" ]; then
            ./check_header.sh $pr_files
          else
            echo "No relevant files to check."
          fi
